### ISSUE TITLE
Nothing happening on /ar toggle

### ISSUE THREAD

**Issue by sabanim** [Alastair-Scott/AltReps#10] opened 2021-03-15 14:56 UTC
I get nothing when I use /ar toggle or the both buttons(minimap or on rep pane.)  Shadowlands Retail, no other addons loaded.  Using wowup.io to manage and curse as the provider.

**Comment by Alastair-Scott** [comment] 2021-03-19 16:39
Hi Sabanim, I'm sorry that you're experiencing this issue. I've just done a new release where I've updated the game version (9.0.2 -> 9.0.5) which may fix this issue for you.

If not, could you please try running ```/console scriptErrors 1``` to get WoW to report any errors when you try to open my addon and then paste the error here? (To stop the error messages after, you can run ```/console scriptErrors 0```)

Thanks!

**Comment by sabanim** [comment] 2021-03-19 17:35
Thanks for the reply!
Here is the info you requested. 

Message: Interface\AddOns\AltReps\Core.lua:2225: attempt to compare number with nil
Time: Fri Mar 19 13:22:54 2021
Count: 1
Stack: Interface\AddOns\AltReps\Core.lua:2225: attempt to compare number with nil
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "@Interface\AddOns\AltReps\Core.lua"]:2225: in function <Interface\AddOns\AltReps\Core.lua:2188>
[string "=[C]"]: in function `sort'
[string "@Interface\AddOns\AltReps\Core.lua"]:2145: in function `sortedPairs'
[string "@Interface\AddOns\AltReps\Core.lua"]:1278: in function `GetTooltip'
[string "@Interface\AddOns\AltReps\Core.lua"]:1515: in function `ToggleVisibility'
[string "@Interface\AddOns\AltReps\Core.lua"]:1143: in function `OnClick'
[string "@Interface\AddOns\LibDBIcon-1.0\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...AddOns\LibDBIcon-1.0\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>
[string "=[C]"]: ?

Locals: errMsg = "Interface\AddOns\AltReps\Core.lua:2225: attempt to compare number with nil"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Alastair-Scott** [comment] 2021-03-19 19:25
Thanks for that! I think I've found the issue and I'll look to get that fixed in a moment.

Would be able to log onto another character with the addon enabled and check to see if that fixes the issue?

I think the issue is when I'm trying to order the characters tracked by the addon and a second character hasn't been tracked.

**Comment by Alastair-Scott** [comment] 2021-03-19 20:09
Pretty sure I've now replicated the issue and have a fix that should be live shortly.

Could you please let me know if v2.7.2 fixes your issue? (Once it updates on Curse at any rate)

Thanks!

**Closed as completed** 2021-07-01 08:58 UTC
Labels: :bug: Bug
